#pragma once

#define MAXEXP_OFFSET_LEFT 50
#define MAXEXP_OFFSET_RIGHT 50
#define MAXEXP_OFFSET_TOP 120
#define MAXEXP_OFFSET_BOTTOM 100

#define EXP_OFFSET_LEFT 52
#define EXP_OFFSET_RIGHT 52
#define EXP_OFFSET_TOP 118
#define EXP_OFFSET_BOTTOM 102